<a href="https://colab.research.google.com/github/MusadaqTanvir/TensforFlowCodes/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamentals of tensors using Tensorflow

More specifically we are going to cover:
* Introduction to tensors
* Getting information from tensor
* Manipulating Tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular python function)
* Using GPU or TPU with Tensorflow
* Exercises to try for yourself

## Introduction to Tensors

In [2]:
# importing tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [6]:
# creating tensors with tf.constants()
scalers = tf.constant(10,tf.int64)
scalers

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [7]:
# Check the number of dimensions of tensor(ndim stands for number of dimensions)
scalers.ndim

0

In [8]:
#creating a vector
vector = tf.constant([10,20,30],tf.int64)
vector

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([10, 20, 30])>

In [9]:
# Dimension of vector
vector.ndim

1

In [10]:
#Creat a matrix of tensor
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
#creating another matrix with parameter of dtype
another_matrix = tf.constant([[10.,10.],[20.,20.],[1.,2.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [20., 20.],
       [ 1.,  2.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [14]:
# Lets' create another tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
tensor.ndim

3

What we've created so far:
* Scaler: a single number
* Vector: a number with direction(windspeed and direction)
* Matrix: a 2-dimension array of numbers
* Tensor: an n-dimensional array of numbers(Where n can be any number 0->....)

# tf.variable

Creating tensors with tf.Variable()

In [17]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,10])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

If we want to change tensor we have to call its .assign method we can't do that with indexing as in python

In [18]:
# Let's take an example
changeable_tensor[0] = 7
# this will throw an error of assignment type

TypeError: 'ResourceVariable' object does not support item assignment

In [19]:
#Lets use built-in method to assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [20]:
# Let's try to change the unchangeable tensor
unchangeable_tensor[0].assign(10)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating Random Tensor

**Note:** Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors,as Tensorflow does this for you.However, if in doubt, use tf.constant and changed it later.

Random Tensors are tensors of some arbitrary size which contain random numbers

In [21]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

# Shuffle the order of elements in tensor

This is valuable(when you want to you shuffle your data So the inherent order doesn't effect learning)

 * **Randomly shuffles along its first dimension**

In [25]:
notshuffled_tensor = tf.constant([[10,7],
                                 [3,4],
                                 [2,5]])
notshuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [26]:
# Lets shuffle the notshuffled tensor
tf.random.shuffle(notshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [34]:
# By setting seed value
tf.random.set_seed(42)
tf.random.shuffle(notshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [35]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [36]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.7402308], shape=(1,), dtype=float32)
tf.Tensor([0.803156], shape=(1,), dtype=float32)


In [39]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [42]:
tf.random.shuffle(notshuffled_tensor,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [45]:
# But to remain consize with randomness
# set global level random seed
tf.random.set_seed(20)
tf.random.shuffle(notshuffled_tensor,seed=20)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Random shuffling is used to make the data more balance and and set the weights and biases of model in same order throughout its execution and each time its gete executed.

# Other ways to make tensors

In [46]:
tf.ones([3,2],dtype=tf.int64)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]])>

In [47]:
#creating tensors with zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy Array into Tensors
The main difference between numpy array and tensors is that these tensors can be run on GPU that is much faster as compared to CPU

In [49]:
# we can convert numpy array into tensor
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [51]:
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>