<a href="https://colab.research.google.com/github/MusadaqTanvir/TensforFlowCodes/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamentals of tensors using Tensorflow

More specifically we are going to cover:
* Introduction to tensors
* Getting information from tensor
* Manipulating Tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular python function)
* Using GPU or TPU with Tensorflow
* Exercises to try for yourself

## Introduction to Tensors

In [58]:
# importing tensorflow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.15.0


In [ ]:
# creating tensors with tf.constants()
scalers = tf.constant(10,tf.int64)
scalers

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [ ]:
# Check the number of dimensions of tensor(ndim stands for number of dimensions)
scalers.ndim

0

In [ ]:
#creating a vector
vector = tf.constant([10,20,30],tf.int64)
vector

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([10, 20, 30])>

In [ ]:
# Dimension of vector
vector.ndim

1

In [ ]:
#Creat a matrix of tensor
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#creating another matrix with parameter of dtype
another_matrix = tf.constant([[10.,10.],[20.,20.],[1.,2.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [20., 20.],
       [ 1.,  2.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets' create another tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scaler: a single number
* Vector: a number with direction(windspeed and direction)
* Matrix: a 2-dimension array of numbers
* Tensor: an n-dimensional array of numbers(Where n can be any number 0->....)

# tf.variable

Creating tensors with tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,10])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

If we want to change tensor we have to call its .assign method we can't do that with indexing as in python

In [ ]:
# Let's take an example
changeable_tensor[0] = 7
# this will throw an error of assignment type

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#Lets use built-in method to assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try to change the unchangeable tensor
unchangeable_tensor[0].assign(10)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating Random Tensor

**Note:** Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors,as Tensorflow does this for you.However, if in doubt, use tf.constant and changed it later.

Random Tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

# Shuffle the order of elements in tensor

This is valuable(when you want to you shuffle your data So the inherent order doesn't effect learning)

 * **Randomly shuffles along its first dimension**

In [ ]:
notshuffled_tensor = tf.constant([[10,7],
                                 [3,4],
                                 [2,5]])
notshuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Lets shuffle the notshuffled tensor
tf.random.shuffle(notshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# By setting seed value
tf.random.set_seed(42)
tf.random.shuffle(notshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.7402308], shape=(1,), dtype=float32)
tf.Tensor([0.803156], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
tf.random.shuffle(notshuffled_tensor,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# But to remain consize with randomness
# set global level random seed
tf.random.set_seed(20)
tf.random.shuffle(notshuffled_tensor,seed=20)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Random shuffling is used to make the data more balance and and set the weights and biases of model in same order throughout its execution and each time its gete executed.

# Other ways to make tensors

In [ ]:
tf.ones([3,2],dtype=tf.int64)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]])>

In [ ]:
#creating tensors with zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy Array into Tensors
The main difference between numpy array and tensors is that these tensors can be run on GPU that is much faster as compared to CPU

In [ ]:
# we can convert numpy array into tensor
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information From Tensors
* Shape
* Size
* Rank
* Axis or dimensions

In [ ]:
# Create a Rank 4 tensor
Rank_4T = tf.constant([[[[10,20]]]])
tf.rank(Rank_4T)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
# another Way to create the above method
Rank_4TT = tf.zeros(shape=[2,3,4,5])
Rank_4TT

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
Rank_4TT[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
Rank_4TT[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
Rank_4TT[1][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
Rank_4TT.shape, tf.rank(Rank_4TT)

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
tf.size(Rank_4TT)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# Getting various attributes of tensor
print("Data Type of Tensor",Rank_4TT.dtype)
print("Shape of Tensor",Rank_4TT.shape)
print("Dimension of Tensor",Rank_4TT.ndim)
print("Elements Along First Axis of Tensor",Rank_4TT.shape[0])
print("Elements along last axis of Tensor",Rank_4TT.shape[-1])
print("Total Size of Tensor",tf.size(Rank_4TT).numpy())

Data Type of Tensor <dtype: 'float32'>
Shape of Tensor (2, 3, 4, 5)
Dimension of Tensor 4
Elements Along First Axis of Tensor 2
Elements along last axis of Tensor 5
Total Size of Tensor 120


# Indexing Tensors
Tensors can be indexed just ike python lists

In [ ]:
# Get the first 2 elements of each dimension
Rank_4TT[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get each dimension from each index except from the final one
Rank_4TT[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
Rank_4TT[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create rank 2 tensor(2 dimension)
rank_2_tensor = tf.zeros(shape=(2,2))

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
# Getting the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
# Add in Extra dimension in tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
rank_4_tensor = rank_3_tensor[...,tf.newaxis]
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]]],


       [[[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 mean expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]]], dtype=float32)>

# Manipulating Tensors (Tensor Operations)
**Basic operations**

In [ ]:
tensor = tf.constant([[10,7],[7,10]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

In [ ]:
# Original tensor remain unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# We can also use function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 70, 100]], dtype=int32)>

In [ ]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

In [ ]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-3,  0]], dtype=int32)>

# Matrix Multiplication of Tensor

In [ ]:
tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [ ]:
X = tf.constant([[1,2],[3,4],[5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
Y = tf.constant([[1,2],[3,4],[5,6]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.linalg.matmul(X,Y,transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [ ]:
# We can also do multiplication by taking transpose explicitly
#Lets try this one
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.linalg.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [ ]:
# Lets reshape the first matrix and then mulitpy
tf.linalg.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.transpose(X), tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

# The Dot Product
* tf.linalg.matmul()
* tf.tensordot()

* Tensors are transposed rather than reshaped during matrix multiplication between tensors

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

# Change the data type of tensor

In [3]:
# Create a tensor with the data type of float32
B = tf.constant([1.,8.,10])
B.dtype

tf.float32

In [4]:
# Changing the dtype from float32 to float16
B = tf.cast(B,dtype=tf.float16)
B.dtype

tf.float16

# Aggregating tensors
Aggregating tensors = condensing them from multiple values down to smaller amount of values

In [5]:
# Get the Absolute value
D = tf.constant([-10,-15])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10, -15], dtype=int32)>

In [6]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

Let's go through the following terms of aggregating:
* Get the minimum
* Get the maximum
* Get the mean
* Get the sum of tensor

In [7]:
# Creating a random tensor
import numpy as np
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([65, 69, 81,  4, 46, 42, 61, 99, 29, 85, 58, 63,  1, 57,  7, 72, 85,
       66, 13, 13, 81, 44, 30, 69, 26, 78, 52, 19, 48, 48, 91, 23, 60,  7,
       81, 98, 34, 97, 40, 39, 79, 70, 20, 65, 96, 41, 71, 37, 73, 49])>

In [8]:
tf.size(E),E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [9]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [10]:
# Find the Maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [11]:
# Find the mean of tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [12]:
# Find the sum of tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2682>

In [16]:
# Find the variance and standard deviation of the tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=732.1504>

In [19]:
# Find the STD
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.058277>

### We can also acheive that via probability class of tensorflow

In [20]:
import tensorflow_probability as tfp

In [21]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=732>

In [26]:
tfp.stats.stddev(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.058277>

## Find the positional Min and Max

In [29]:
# Creating random tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [31]:
# Max finding
tf.argmax(F) # it returns the index of maximum value

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [32]:
# Value at index of 42
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [33]:
# Same via math module
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [34]:
# Minmum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [35]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [36]:
tf.math.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Sequeezing a Tensor
Removing All single Dimenions

In [38]:
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [39]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [41]:
G_squeezed = tf.squeeze(G)

In [42]:
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

In [44]:
G_squeezed.shape

TensorShape([50])

# One Hot Encoding Tensors

In [49]:
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## Squaring, Log, Square root

In [51]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [52]:
# How to square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [55]:
tf.math.sqrt(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [57]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

# Tensors and Numpy
* Tensor interacts beautifully with Numpy Arrays

In [59]:
# Create a tensor directly from numpy array
J = tf.constant(np.array([1,2,3,4,5]))
J

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [60]:
# Conver the tensors back to Numpy Array
J.numpy()

array([1, 2, 3, 4, 5])

In [61]:
# The default data type of each are slightly different
numpy_j = tf.constant(np.array([3.,7.,10.])) # This return the float64
tensor_J = tf.constant([1.,2.,3.]) # this return the float32
numpy_j.dtype,tensor_J.dtype

(tf.float64, tf.float32)