<a href="https://colab.research.google.com/github/MusadaqTanvir/test_repo/blob/main/TensorFlow_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# we are forcing colab to use this version of tensorflow
%tensorflow_version 2.x


Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


**Creating** **Tensor**
Below is an example of how to create basic tensors

In [5]:
string = tf.Variable("This is string",tf.string)
number = tf.Variable(100,tf.int16)
floating = tf.Variable(3.14,tf.float32)

These are scaler values

**Rank/Degree of Tensors**
Another word of rank is degree. These term simply means the number of dimensions involved in tensors.What we created above is tensor of rank 0 also known as 0.
Now we will create of tensors of higher degree/dimensions

In [9]:
rank1_tensor = tf.Variable(['This',"test","Me"],tf.string)
rank2_tensor = tf.Variable([['He','Hello','Hi'],['Now','New','No']],tf.string)

**To determine the rank** of tensor use the following code

In [10]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

**Shape of Tensors**
Now we know about the rank of tensors now we will know about the shape of tensors.There are often many shapes that have same number of elements, making it convienent to be able to change the shape of tensor.Shape actually tells that how many items have in each dimension.
The example below shows the how to change the shape of tensors.

In [12]:
rank2_tensor.shape

TensorShape([2, 3])

**Changing Shape**
The number of elements of a tensor is the product of sizes of all of its shapes.The below example elaborate how to change the shape of tensor

In [19]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2,[3,-1])

In [15]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [16]:
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [17]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

**Types of Tensors***
Before we will go to far we will mention there that there are different types of tensors. These are most commonly used and we will talk more in depth about each as they are used.


<ul>
  <li>Variable</li>
  <li>Constants</li>
  <li>PlaceHolder</li>
  <li>SparseTensor</li>
</ul>

With the exception of **Variable** all of these tensors are immutable, cannot be changed during execution,

**Evaluating Tensors**
There will be sometime throughout this guide that we need to evaluate a tensor. In other words, get its value. Since tensors represents a partially complete computation we will sometimes need to run whats called a session to evaluate the tensor.
There are different ways to achieve this.

